name: Compile PDFs

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: thomasweise/texlive
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build docs
        run: |
          make 
          mkdir public
          cp example/cv.pdf public/cv.pdf
                    cat > public/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>José Faria Curriculum Vitae</title>
            </head>
            <body>
              <iframe src="cv.pdf" width="100%" height="100%"> </iframe>
            </body>
          </html>
          EOL

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
