name: Compile PDFs

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-18.04
    container: thomasweise/texlive

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create public directory to host HTML
        run: mkdir public

      - name: Convert tex to HTML
        uses: docker://pandoc/latex:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=public/index.html
            -f latex
            examples/cv.tex   

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
